### ISSUE TITLE
Compilation Error on line 1886 of LibLog.cs

### ISSUE THREAD

**Issue by kendallmiller** [damianh/LibLog#43]
While working on another issue I'm seeing a compilation error on this line:

```cs
            if (formatParameters == null || !formatParameters.Length == 0)
            {
                return messageBuilder;
            }
```

Due to the ! in front of "formatParameters.Length".  The specific compilation error in VS 2013 is:
> Error	1	Operator '!' cannot be applied to operand of type 'int'	C:\Development\Git\LibLog\src\LibLog\LibLog.cs	1886	45	LibLog

which would be trivial to resolve by wrapping the expression in parenthesis, but I think the logic is wrong - I think the goal was to test for null or zero length in which case the ! is a typo.

**Comment by damianh** [comment]
This is fixed in latest master.

Bad merge sry.

**Comment by damianh** [comment]
Fixed here https://github.com/damianh/LibLog/commit/ee5ce294f71a0e25ae2d77293d3f88a49aa9c793
